<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/admin_options/localization/<lang>.inc                         |
 |                                                                       |
 | Localization file of the Roundcube Webmail admin_options plugin       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

*/

$labels = array();
$labels['administration'] = 'Administración';
$labels['noadminoptions'] = 'No Admin options available';
$labels['section'] = 'Administración';

?>
